name: touchsdf-core
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy
  - scipy
  - pandas
  - pillow
  - matplotlib
  - jupyterlab
  - pytorch=2.0.1
  - openblas
  - libgcc-ng
  - pip:
      - git+https://github.com/facebookresearch/pytorch3d.git
      - git+https://github.com/ac-93/tactile_gym.git@deepsdf#egg=tactile_gym
      - tqdm
      - tensorboard
      - trimesh
      - opencv-python
      - pybullet
      - gym
      - scikit-learn
      - plotly
      - point_cloud_utils